
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - "mvn clean package"
  tags:
    - riseclipse

# deploy is not restricted to master because of dependencies beween plug-ins
deploy:
  stage: deploy
  script:
    - "mvn deploy"
  tags:
    - riseclipse

